import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ContextProvider from '@/components/context-provider';

import './styles/globals.css';

import SideNav from '@/components/side-nav';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={inter.className}>
        <ContextProvider>
          <div className="flex">
            <SideNav />
            <div className="w-full ">
              <div className="sm:h-screen overflow-auto ">
                <div className="w-full relative">
                  <div className="w-full">{children}</div>
                </div>
              </div>
            </div>
          </div>
          <Toaster theme='system' />
        </ContextProvider>
      </body>
    </html>
  );
}
